# -*- coding: utf-8 -*-
"""
Created on Fri Dec 27 22:51:51 2024

@author: chris
"""

import pandas as pd
import dash_bootstrap_components as dbc

def generate_dropdown_menu_item(dropdown_item):
    '''
    Function to create dropdown menu items inside the function to create the dropdowns
    (Used to avoid: TypeError: Object of type generator is not JSON serializable)
    
    Inputs:
        dropdown_item: string to be converted into a dash bootstrap component DropdownMenuItem
    Outputs:
        dash bootstrap commponet DropdownMenuItem
    '''
    return dbc.DropdownMenuItem(children=dropdown_item,
                                id = f'dropdown_item_{dropdown_item}')
def generate_dropdown_menu(dropdown_df,tab_prefix,group_name):
    '''
    Function to generate dropdown menus
    
    Inputs:
        dropdown_df: a dataframe with the dropdown menu items as the index
        tab_prefix: string used as part of the component id
        group_name: string tag included in the text displayed in the dropdown menu prompt as well as the element id
    Outputs:
        dash boostrap component DropdownMenu with DropdownMenuItem entries generated by the generate_dropdown_menu_item function
    '''
    return dbc.DropdownMenu(label = f'Select a {group_name} stock...',
                            id = f'{tab_prefix}_dropdown_{group_name}',
                            children = [generate_dropdown_menu_item(dropdown_item) for dropdown_item in dropdown_df.index.to_list()])

def generate_plotly_plot():
    '''
    Placeholder function for generating plot for stocks / indices
    '''
    pass

def get_treasury_data():
    '''
    Placeholder function for get request for treasury data via API
    '''
    pass

def sup_func_main():
    pass

if __name__ == '__main__':
    sup_func_main()